# Generated by Django 6.0.7 on 2026-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetail_avatar_alter_userdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
