# Generated by Django 6.0.7 on 2026-08-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunlik', models.TextField(blank=True, max_length=255, null=True)),
                ('haftalik', models.TextField(blank=True, max_length=255, null=True)),
                ('oylik', models.TextField(blank=True, max_length=255, null=True)),
                ('yillik', models.TextField(blank=True, max_length=255, null=True)),
                ('goal', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userdetail')),
            ],
        ),
    ]
