# Generated by Django 6.0.7 on 2026-08-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
