# Generated by Django 6.0.7 on 2026-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyi', models.CharField(max_length=100)),
                ('vazni', models.CharField(max_length=100)),
                ('maqsadi', models.CharField(max_length=100)),
            ],
        ),
    ]
