# Generated by Django 6.0.7 on 2026-08-19 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='buyi',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='vazni',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='maqsadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
