# Generated by Django 6.0.7 on 2026-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_remove_userquestion_buyi_remove_userquestion_vazni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='buyi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='vazni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
